# Generated by Django 5.1.5 on 2025-01-22 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('createdAt', models.DateField()),
                ('updatedAt', models.DateField()),
                ('deletedAt', models.DateField()),
            ],
        ),
    ]
